services:
  neo4j:
    image: neo4j:2026.03-community-trixie
    container_name: neo4j
    ports:
      - "7474:7474" # Browser
      - "7687:7687" # Driver
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      # Disables the annoying welcome message
      - NEO4J_browser_post__connect__cmd=clear
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    restart: unless-stopped
